# retrieval settings
MODEL:
  TYPE: "cls"
  ACTIVATE: "relu"
  BACKBONE: "resnest50d"
  WEIGHTS: ""
  CLASSES: 403
TRAIN:
  DATASETS: "/media/cobot/4e4a7518-760a-46bb-a065-cbdcce966213/changshaTobacco/triplet/dataset/"
  INPUT_BATCH: 36
  NUM_WORKERS: 4
  INPUT_CHANNEL: 3
  INPUT_WIDTH: 320
  INPUT_HEIGHT: 320
  TRANSFORM: "DefaultTransform"
  APEX: False
INFERENCE:
  TRANSFORM: "InferTransform"
TEST:
  DATAPATH: ""
SOLVER:
  OPTIMER: "sgd"
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.0002
  WEIGHT_DECAY: 0.0001
  MAX_ITER: 200
  WARMUP_MULTIPLIER: 10
  WARMUP_ITERS: 1000
LOSS:
  NAME: "CELoss"
OUTPUT:
  DIR: "/media/cobot/4e4a7518-760a-46bb-a065-cbdcce966213/changshaTobacco/triplet/cls"
  SAVE_SUFFIX: "0919"
  SAVE_INTERVAL: 2
GPUS:
  CUDA_VISIBLE_DEVICES: "'0'"