# retrieval settings
MODEL:
  TYPE: "cls"
  ACTIVATE: "relu"
  BACKBONE: "resnest50d"
  WEIGHTS: ""
  CLASSES: 403
  METIRC:
    DIM: 256
    POOLING_LAYER: 'gem'
TRAIN:
  DATASETS: ""
  NUM_WORKERS: 4
  INPUT_CHANNEL: 3
  INPUT_WIDTH: 320
  INPUT_HEIGHT: 320
  TRANSFORM: "DefaultTransform"
  METRIC:
    NUM_CLASSES: 6
    NUM_SAMPLES: 6
    OUTER_HARDSAMPLER: True
    INTER_HARDSAMPLER: False
    INTER_HARDSAMPLER_THRED: 0.99

INFERENCE:
  TRANSFORM: "InferTransform"
TEST:
  DATAPATH: ""
SOLVER:
  OPTIMER: "sgd"
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  MAX_ITER: 200
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
LOSS:
  NAME: "CircleLoss"
OUTPUT:
  DIR: ""
  SAVE_SUFFIX: "0919"
  SAVE_INTERVAL: 2
GPUS:
  CUDA_VISIBLE_DEVICES: "'0'"